root_dir = "~/.daybegin"
manifest_path = "~/.daybegin/daybegin/Cargo.toml"
work_dir = "~/Code/translucent/"
git_branch = "main"
shell_commands = ["make nuke", "pnpm install", "make all", "pnpm dev"]
applications = ["Docker", "Visual Studio Code"]
