root_dir = "~/.daybegin"
manifest_path = "~/.daybegin/daybegin/Cargo.toml"
work_dir = "~/my_project"
git_branch = "main"
shell_commands = ["make clean", "make build"]
applications = ["Docker", "Visual Studio Code"]
